### ISSUE TITLE
Unset GameEvent type in referee message

### ISSUE THREAD

**Issue by rolfvdhulst** [RoboCup-SSL/ssl-game-controller#15] opened 2020-05-09 18:09 UTC
I was testing with the latest release (2.0.7)

To reproduce:
-Run the gamecontroller without vision available:
-Run a penalty (Stop->Penalty->NormalStart)
-Let the time (10 seconds) run out

After this happens, we get the following error on our system receiving the referee messages:

[libprotobuf ERROR google/protobuf/message_lite.cc:122] Can't parse message of type "proto.Referee" because it is missing required fields: game_events[0].type

In any case, I don't think the GameController should send unparseable messages so I think this is a valid issue.

**Comment by g3force** [comment] 2020-05-09 19:08
Thx for reporting.

In this scenario, a new game event "PenaltyKickFailed" is send out, which you probably have not yet added to the protobuf file.

I can reproduce the issue in Java with the same error message. The problem is, that the type field is a required field, so the parser prefers to throw an exception. If I make it optional, the message gets parsed.
The parser seems to be fine with missing the PenaltyKickFailed Event type itself.

I'd like to keep compatibility, so I will define new fields for the game event and proposed game event lists in the referee message. That way, old clients will not receive any game events, but at least they won't run into an error.

**Comment by g3force** [comment] 2020-05-10 10:54
Should be fixed in v2.0.0-rc2.

**Closed by g3force** 2020-05-10 10:54 UTC
